baseURL: "https://raleighwi.se"
title: Raleigh Wise
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Postography
                  url: archives
                  weight: 11
                - name: About me
                  url: aboutme
                  weight: 10
                - name: Search
                  url: search/
                  weight: -1
                - name: Projects
                  url: projects
                  weight: 9
                - name: Links
                  url: https://ll.raleighwi.se
                  weight: 12


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "l3gacyb3ta's blog/portfolio"
    author: l3gacy
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Raleigh Wise
        subtitle: "Hello! I’m Raleigh (he/they), I am a developer in high school. <br>
                    I am skilled in <strong><a href='https://www.python.org/'>Python</a></strong>, <strong><a href='https://flask.palletsprojects.com/en/1.1.x/'>Flask</a></strong>, <strong><a href='https://www.djangoproject.com/'>Django</a></strong>, <strong><a href='https://isocpp.org/'>C++</a></strong>, <strong><a href='https://www.linux.org/'>Linux</a></strong>, and <strong><a href='https://git-scm.com/'>git</a></strong>.<br>
                    Currently I'm learning <strong><a href='https://crystal-lang.org'>Crystal</a></strong>, and <strong><a href='https://nextjs.org/'>Next.js</a></strong> + <strong><a href='https://reactjs.org/'>React</a></strong>!"
        imageUrl: "/images/avatar.png"
        imageTitle: avatar
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Blog
              url: posts
            - name: Projects
              url: projects
            - name: About me
              url: aboutme

    homeInfoParams:
        Title: "l3gacyb3ta"
        Content: >
                    Hello! I’m Raleigh (he/they), I do backend and service development.

    socialIcons:
        - name: github
          url: "https://github.com/l3gacyb3ta"
        
        - name: keybase
          url: "https://keybase.io/l3gacyb3ta"

        - name: RSS
          url: "index.xml"


    assets:
        favicon: "/images/favicon.ico"
        favicon16x16: "/images/favicon-16x16.png"
        favicon32x32: "/images/favicon-32x32.png"
        apple_touch_icon: "/images/apple-touch-icon.png"
        safari_pinned_tab: "/images/safari-pinned-tab.svg"


taxonomies:
    tag: tags
    series: series

markup:
     goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
